description: A new Flutter project.

dependencies:
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  http: ^0.12.0+4
  scrollable_positioned_list: ^0.1.4

dev_dependencies:
  build_runner: ^1.9.0
  flutter_launcher_icons: ^0.7.4
  json_serializable: ^3.3.0

environment:
  sdk: ">=2.7.0 <3.0.0"

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Museo Sans Cyrl
      fonts:
        - asset: assets/fonts/museo_sans_cyrl.ttf
  uses-material-design: true

flutter_icons:
  android: "ic_launcher" 
  ios: true
  image_path: "assets/icon/icon.png"

name: taaqeem

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
